config/routes.rb
Rails.application.routes.draw do
  get "home/top", to: "home#top"

  get "rooms/search", to: "rooms#search"
  resources :rooms
  
  get "reservations/confirm", to: "reservations#confirm"
  resources :reservations

  get "users/account", to: "users#account"
  get "users/profile", to: "users#profile"
  resources :users, only: [:update]
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  devise_scope :user do
    # ワンクリックでログアウトする仕様
    get "/users/sign_out", to: "devise/sessions#destroy"
  end    

end

app/models/reservation.rb
class Reservation < ApplicationRecord
    validates :start_day, presence: true
    validates :end_day, presence: true
    validates :people, presence: true

    validate :start_end_check       # 開始日＜終了日　かどうか
    validate :start_today_check     # 本日＜開始日　かどうか

    belongs_to :room

    def start_end_check
      if start_day.present? && end_day.present?
        if end_day < start_day
          errors.add(:end_day, "は開始日より後の日付を入力してください")
        end
      
      end
      
    end

    def start_today_check
      if start_day.present? && end_day.present?
        if start_day < Date.today
          errors.add(:start_day, "は本日以降の日付を入力してください")
        end

      end
      
    end


end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @reservations = Reservation.all
  end 

  def confirm
    @reservation = Reservation.new(params.require(:reservation).permit(:start_day, :end_day, :people, :room_id))
    @room = Room.find_by(id: @reservation.room_id)

    if @reservation.invalid?
      # flash[:notice] = "error!"
      render "rooms/show"
    
    end
    if @reservation.start_day.present? && @reservation.end_day.present?
      @total_day = (@reservation.end_day - @reservation.start_day).to_i
      @total_price = @total_day * (@room.room_charge).to_i
    end

  end

  def show
    @reservation = Reservation.find_by(id: params[:id])
    @room = Room.find_by(id: @reservation.room_id)
    
  end

  def create
    @reservation = Reservation.new(params.require(:reservation).permit(:start_day, :end_day, :people, :room_id, :total_price))

    if @reservation.save
      flash[:notice] = "Reservation was successfully created."
      redirect_to reservation_path(@reservation.id)

    end
    
  end

  def destroy
    @reservation = Reservation.find_by(id: params[:id])
    @reservation.destroy
    flash[:notice] = "reservation was successfully deleted."
    redirect_to :reservations
  end


end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/confirm.html.erb
<div class = "reservation-confirm">
    <div class = "reservation-confirm-contents">
        <h2>予約内容確認</h2>
        <h3>¥ <%= @room.room_charge %> / 日</h3>

        <%= form_with model: @reservation do |f| %>
            <% # 前回入力したパラメータはhiddenで記載しないと拾えない？ %>
            <%= f.hidden_field :start_day, value: @reservation.start_day %>
            <%= f.hidden_field :end_day, value: @reservation.end_day %>
            <%= f.hidden_field :people, value: @reservation.people %>
            <%= f.hidden_field :room_id, value: @room.id %>
            <%= f.hidden_field :total_price, value: @total_price %>            
            <%= f.hidden_field :created_at, value: @reservation.created_at %>
            <%= f.hidden_field :updated_at, value: @reservation.updated_at %>
            

            <%= f.label :start_day, "開始日" %>
            <%= f.date_field :start_day, disabled: true, class: "confirm-input-area" %>
            <%= f.label :end_day, "終了日" %>
            <%= f.date_field :end_day, disabled: true, class: "confirm-input-area" %>
            <div class = "total_day">使用日数：<%= @total_day %> 日</div>
            <div class = "people">人数：<%= @reservation.people %> 人</div>
            <%= f.label :total_price, "合計金額" %>
            <%= f.text_field :total_price, value: @total_price, disabled: true, class: "confirm-input-area" %>
            <p>上記内容でよろしければ「予約を確定」を押してください</p>

            <%= f.submit "予約を確定", class: "reservation-btn" %>
            <%= link_to "ルーム詳細に戻る", room_path(@room.id), class: "return-room-index-btn" %>

        <% end %>

    </div>

</div>

app/views/reservations/index.html.erb
<div class = "reservation-index">
    <h2>予約済ルーム一覧</h2>

    <table class = "table-index">
        <thead>
            <tr>
                <th>ルーム画像</th>
                <th>ルーム名</th>
                <th>ルーム紹介</th>
                <th>合計料金</th>
                <th>開始日</th>
                <th>終了日</th>
                <th>予約確定日時</th>
            </tr>
        </thead>
        <tbody>
            <% @reservations.each do |reservation| %>
                <tr class = "table-index-contents">
                    <td class = "room-pic"><%= link_to image_tag(reservation.room.room_pic.url), room_path(reservation.room_id) %> </td>            
                    <td class = "room-name"><%= link_to "#{reservation.room.room_name}", room_path(reservation.room_id) %> </td>            
                    <td><%= reservation.room.room_introduction %> </td>            
                    <td>¥ <%= reservation.total_price %></td>
                    <td><%= reservation.start_day %></td>
                    <td><%= reservation.end_day %></td>
                    <td><%= reservation.created_at.to_s(:datetime_jp) %></td>
                    <td><%= link_to "削除", reservation, method: :delete, data: {confirm: "本当に削除しますか？"} %></td>
                </tr>
            <% end %>


        </tbody>

    </table>

    </div>

</div>

app/views/reservations/show.html.erb
<% if flash[:notice] %>
    <div class="flash flash-success">
        <%= flash[:notice] %>
    </div>
<% end %>

<div class = "reservation-complete">
    <div class = "reservation-complete-contents">
        <div class = "row">
            <label>予約した部屋</label>
            <div><%= link_to "#{@room.room_name}", room_path(@room.id), class: "room-complete-room-name" %></div>
        </div>
        <div class = "row">
            <label>開始日</label>
            <div><%= @reservation.start_day %></div>
        </div>
        <div class = "row">
            <label>終了日</label>
            <div><%= @reservation.end_day %></div>
        </div>
        <div class = "row-bottom">
            <label>価格</label>
            <div><%= @reservation.total_price %> 円</div>
        </div>
    </div>

</div>