config/routes.rb
Rails.application.routes.draw do
  get "home/top", to: "home#top"

  get "rooms/search", to: "rooms#search"
  resources :rooms
  
  get "reservations/confirm", to: "reservations#confirm"
  resources :reservations

  get "users/account", to: "users#account"
  get "users/profile", to: "users#profile"
  resources :users, only: [:update]
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  devise_scope :user do
    # ワンクリックでログアウトする仕様
    get "/users/sign_out", to: "devise/sessions#destroy"
  end    

end

app/models/room.rb
class Room < ApplicationRecord
    validates :room_name, presence: true
    validates :room_introduction, presence: true
    validates :room_charge, presence: true
    validates :room_address, presence: true
    validates :room_pic, presence: true

    has_many :reservations, dependent: :destroy, foreign_key: "room_id"

    mount_uploader :room_pic, RoomPicUploader
    
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :new]

  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new
  end

  def show
    @room = Room.find_by(id: params[:id])
    @reservation = Reservation.new

  end  

  def create
    @room = Room.new(params.require(:room).permit(:room_name, :room_introduction, :room_charge, :room_address, :room_pic))
    if @room.save
      flash[:notice] = "Room was successfully created."
      redirect_to :rooms
    else
      render "new"
    end

  end

  def destroy
    @room = Room.find_by(id: params[:id])
    @room.destroy
    flash[:notice] = "Room was successfully deleted."
    redirect_to :rooms
  end

  def search
    if params[:area]
      @rooms = Room.where(["room_address like?", "%#{params[:area]}%"])
      @search_total = Room.where(["room_address like?", "%#{params[:area]}%"]).count
    elsif params[:keyword]
      @rooms = Room.where(["room_name like? or room_address like? or room_introduction like?" , "%#{params[:keyword]}%", "%#{params[:keyword]}%", "%#{params[:keyword]}%" ])
      @search_total = Room.where(["room_name like? or room_address like? or room_introduction like?" , "%#{params[:keyword]}%", "%#{params[:keyword]}%", "%#{params[:keyword]}%" ]).count
    else
    end
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/index.html.erb
<% if flash[:notice] %>
    <div class="flash flash-success">
        <%= flash[:notice] %>
    </div>
<% end %>

<div class = "room-index">

    <h2>登録済ルーム一覧</h2>

    <table class = "table-index">
        <thead>
            <tr>
                <th>ルーム画像</th>
                <th>ルーム名</th>
                <th>ルーム紹介</th>
                <th>料金</th>
                <th>作成日</th>
            </tr>
        </thead>
        <tbody>
            <% @rooms.each do |room| %>
                <tr class = "table-index-contents">
                    <td class = "room-pic"><%= link_to image_tag(room.room_pic.url), room %></td>
                    <td class = "room-name"><%= link_to "#{room.room_name}", room %></td>
                    <td class = "room-introduction"><%= room.room_introduction %></td>
                    <td>¥ <%= room.room_charge %></td>
                    <td><%= room.created_at.to_s(:datetime_jp) %></td>
                    <td><%= link_to "削除", room, method: :delete, data: {confirm: "本当に削除しますか？"} %></td>
                </tr>

            <% end %>

        </tbody>

    </table>

</div>

app/views/rooms/new.html.erb
<div class = "room-new">

    <div>
    
    </div>

    <div class = "room-new-contents">

        <% @room.errors.full_messages.each do |message| %>
            <%= message %><br>
        <% end %>

        <%= form_with model: @room do |f| %>    
            <table class = "table-new">
                <tr><h3>ルーム情報登録</h3></tr>
                <tr>
                    <th><%= f.label :room_name, "ルーム名" %><span class = "must-mark">必須</span></th>
                    <td><%= f.text_field :room_name, placeholder: "ルーム名を入力", class: "input-area" %></td>
                </tr>
                <tr>
                    <th><%= f.label :room_introduction, "ルーム紹介" %><span class = "must-mark">必須</span></th>
                    <td><%= f.text_area :room_introduction, placeholder: "ルーム説明を入力", class: "textarea" %></td>
                </tr>
                <tr>
                    <th><%= f.label :room_charge, "ルーム料金" %><span class = "must-mark">必須</span></th>
                    <td><%= f.number_field :room_charge, placeholder: "1日あたりの料金を入力", class: "input-area" %></td>
                </tr>
                <tr>
                    <th><%= f.label :room_address ,"住所" %><span class = "must-mark">必須</span></th>
                    <td><%= f.text_field :room_address, placeholder: "住所を入力", class: "input-area" %></td>
                </tr>
                <tr>
                    <th><%= f.label :room_pic, "ルーム画像" %><span class = "must-mark">必須</span></th>
                    <td><%= f.file_field :room_pic, class: "photo-select-area" %></td>
                </tr>
            </table>
            <div>
                <ul>
                    <li><%= f.submit "登録", class: "register-btn" %></li>
                </ul>
            </div>
        <% end %>
    
    </div>
    
    </div>

app/views/rooms/search.html.erb
<div class = "search">
    <div class = "search-contents">
        <h4>検索結果：<%= @search_total %> 件</h4>
        <div class = "search-results">
            <% @rooms.each do |room| %>
                <div class = "search-results-contents">
                    <div class = "search-results-contents-row">
                        <%= link_to room do %>
                            <div><%= image_tag (room.room_pic.url) %></div>
                            <div class = "room-name room-name-row"><%= room.room_name %></div>
                            <div class = "room-address room-address-row"><%= room.room_address %></div>
                            <div class = "room-charge room-charge-row">¥<%= room.room_charge %></div>

                        <% end %>
                    </div>
                </div>

            <% end %>
        </div>
    </div>
</div>

app/views/rooms/show.html.erb
<% @reservation.errors.full_messages.each do |message| %>
    <ul>
        <li class = "error-message"><%= message %></li>
    </ul>
<% end %>

<div class = "room-detail">
    <% # 左半分 %>
    <div class = "room-index-left">
        <% # 写真 %>
        <div class = "room-pic">
            <%= image_tag @room.room_pic.url %>
        </div>

        <% # 左下ボックス %>
        <div class = "room-show">
            <div class = "room-show-icon">
                <% if current_user.icon_img.present? %>
                    <%= image_tag current_user.icon_img.url, class: "login-icon-img" %>
                <% else %>
                    <%= image_tag "https://presite-potepancamp-rails-02.herokuapp.com/assets/default_icon-9263fc59c414b7228d256fc178dcb22183561357950a68f5ad086ba7ee054974.jpg", class: "login-icon-img " %>
                <% end %>              
            </div>
            
            <div class = "room-show-profile">
                <div class = "room-name">
                    <%= @room.room_name %>
                </div>
                <div class = "room-address">
                    <%= @room.room_address %>
                </div>
            </div>
        </div>

        <p class = "room-introduction"><%= @room.room_introduction %></p>
        
    
    </div>

    <% # 右半分 %>
    <div class = "room-index-right">
        <h5>¥ <%= @room.room_charge %> / 日</h5>
        
        <%= form_with model: @reservation, url: reservations_confirm_path, method: :get do |f| %>

            <%= f.hidden_field :room_id, value: @room.id %>

            <%= f.label :start_day, "開始日" %>
            <%= f.date_field :start_day, class: "room-reservation-input-area" %>
            <%= f.label :end_day, "終了日" %>
            <%= f.date_field :end_day, class: "room-reservation-input-area" %>
            <%= f.label :people, "人数" %>
            <%= f.number_field :people, class: "room-reservation-input-area" %>

            <% if user_signed_in? %>
                <%= f.submit "予約する", class: "reservation-btn" %>
            <% else %>
                <%= f.submit "ログイン", class: "reservation-btn" %>
            <% end %>

        <% end %>

    </div>

</div>